version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
  postgres-test:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data-test
